### PR TITLE
New Spellbook orgainization

### PR DESCRIPTION
**Pull request by bobcorey**
Added new directory structure for Spellbook utilities and deleted outdated directories.

### CODE REVIEW

**Comment by lucpeterson** [comment]
Some a.out files were accidentally added. Please delete them.

**Comment by lucpeterson** [comment]
Remove jag_learn stuff

**Comment by lucpeterson** [comment]
Remove added CMakeFiles subdirectories

**Review by lucpeterson — APPROVED** [review]
Looks good to me

**Review by koning — APPROVED** [review]

**Review by ben-bay — APPROVED** [review]

**Pull request merged**
